### ISSUE TITLE
Need to Control Initial start Message Delay in React Chatbotify

### ISSUE THREAD

**Issue by devAmaresh** [tjtanjin/react-chatbotify#18]
Hello,

I am using React Chatbotify for a project and I've encountered an issue. There seems to be a delay before the start message is shown when the chatbot is initialized. I would like to control this delay, ideally setting it to zero so that the start message appears immediately.

I've looked through the documentation and the source code, but I couldn't find a specific setting or property that controls this delay. It's possible that I've missed it, or that this feature is not directly configurable.

Could you please provide some guidance on how to control the delay of the start message in React Chatbotify? If this feature is not currently available, could it be considered for a future update?

**Comment by tjtanjin** [comment]
Hi @devAmaresh, I'm unsure of the delay that you are experiencing. If you hop over to the [documentation website](https://react-chatbotify.tjtanjin.com), the chatbot sends its messages immediately. Are you perhaps able to send a video or elaborate on the issue?

**Comment by devAmaresh** [comment]
https://github.com/tjtanjin/react-chatbotify/assets/141488853/f440215c-6f5e-44ad-969d-2286ceb28879

you can refer to this video ..When the initial start message is shown there is a transition effect (delay) i want a control over it ....

**Comment by tjtanjin** [comment]
> bandicam.2024-03-26.14-54-10-824.mp4 
> you can refer to this video ..When the initial start message is shown there is a transition effect (delay) i want a control over it ....

Are you referring to the animation played for the chat bubbles?

**Comment by tjtanjin** [comment]
> > > bandicam.2024-03-26.14-54-10-824.mp4
> 
> > > you can refer to this video ..When the initial start message is shown there is a transition effect (delay) i want a control over it ....
> 
> > 
> 
> > Are you referring to the animation played for the chat bubbles?
> 
> 
> 
> yes..

I see you have a rather interesting use case where you're building a wrapper around the chatbot. I can understand why you won't want the first message to animate since it is visually disruptive on every edit.

That said, I have never catered this option since for typical uses of a chatbot, the messages should be animated the same way regardless of whether it's the first or last message. I am also not very inclined to add a special option just for the first message because it is very niche.

Not to worry though, I am not leaving you in the lurch. Moving forward, this is how I picture we can resolve this:
- (Me) Add an `animate` boolean field under `userBubble` and `botBubble`
- (You) Use the advance custom bot options and possibly the advance custom messages option to toggle the chat animations on and off

The above solution is general enough to be possibly useful for other use cases and at the same time, provides a solution to your issue. I understand this is more troublesome than a straightforward solution of adding an option to the initial message but it is a good balance between having too niche a feature and addressing your needs.

Let me know your thoughts!

**Comment by devAmaresh** [comment]
I am satisfied with your solution . Looking forward to seeing this enhancement implemented!.
Thank you for your efforts ..

**Comment by tjtanjin** [comment]
> I am satisfied with your solution . Looking forward to seeing this enhancement implemented!.
> 
> Thank you for your efforts ..

No problem! I actually feel the `animate` field would be nice to have. Separately, would you be comfortable reaching out on [discord](https://discord.gg/6R4DK4G5Zh)? I am a little curious about your use case and can also benefit from having you test the build as well 😝

**Comment by devAmaresh** [comment]
> > I am satisfied with your solution . Looking forward to seeing this enhancement implemented!.
> > Thank you for your efforts ..
> 
> No problem! I actually feel the `animate` field would be nice to have. Separately, would you be comfortable reaching out on [discord](https://discord.gg/6R4DK4G5Zh)? I am a little curious about your use case and can also benefit from having you test the build as well 😝

sure

**Comment by tjtanjin** [comment]
Closing this issue for the following reasons:
- Conversation taken to discord
- Test build for the feature has been shared on discord and will go public in the next update
